compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN-}"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
