name: 'Dev Build'
concurrency: dev-build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    timeout-minutes: 15
    env:
      TF_WORKSPACE: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.5
          platforms: linux/arm64

      - name: Setup AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.6.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - run: yarn

      - run: yarn tsup

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Clean yarn cache
        run: yarn cache clean --all

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: cd terraform && terraform validate -no-color
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TF_VAR_is_github_action: 'true'
          TF_VAR_release_id: ${{ github.sha }}

      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve -input=false
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TF_VAR_is_github_action: 'true'
          TF_VAR_release_id: ${{ github.sha }}
