name: Lost Pixel

on:
  pull_request:

jobs:
  lost-pixel-run:
    runs-on: ubuntu-latest
    name: Run
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: |
          yarn dev:prepare
          yarn build-storybook

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.16.0

      - name: Artifacts upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: lost-pixel-artefacts
          path: .lostpixel
          retention-days: 7
