name: 'Manual Push'

on: [workflow_dispatch]

jobs:
  terraform:
    name: 'Terraform'
    concurrency: production
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.5
          platforms: linux/arm64

      - name: Setup AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.5.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - run: yarn

      - run: yarn tsup

      - name: Terraform Init
        id: init
        run: cd terraform && terraform init -input=false
        env:
          TF_WORKSPACE: generator-v2-staging

      - name: Terraform Validate
        run: cd terraform && terraform validate -no-color
        env:
          TF_WORKSPACE: generator-v2-staging
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_is_github_action: 'true'
          TF_VAR_release_id: 'manual-${{ github.ref_name }}'

      - name: Staging Terraform Apply
        run: cd terraform && terraform apply -auto-approve -input=false
        env:
          TF_WORKSPACE: generator-v2-staging
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TF_VAR_is_github_action: 'true'
          TF_VAR_release_id: 'manual-${{ github.ref_name }}'

      - name: Production Terraform Apply
        run: cd terraform && terraform apply -auto-approve -input=false
        env:
          TF_WORKSPACE: generator-v2-production
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          TF_VAR_is_github_action: 'true'
          TF_VAR_release_id: 'manual-${{ github.ref_name }}'
